[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part2"
path = "src/part2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
